### ISSUE TITLE
关于数据的使用问题

### ISSUE THREAD

**Issue by taonlp** [baiyyang/medical-entity-recognition#10]
您好，我看了几篇医学NER的论文，他们都使用了CCKS2017作为实验的数据集，请问这个数据集是没有版权的吗，可以直接在我的论文中使用吗？

**Comment by baiyyang** [comment]
公开的数据集，可以直接使用的


在2021年08月8日 ***@***.***> 写道：

您好，我看了几篇医学NER的论文，他们都使用了CCKS2017作为实验的数据集，请问这个数据集是没有版权的吗，可以直接在我的论文中使用吗？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by taonlp** [comment]
好的 谢谢您
